-- Migration 009: Seed integration pattern analysis workflow, agent, and skills
-- Auto-generated from lintel.domain.seed using domain types
-- Re-run this migration to update built-in definitions

BEGIN;

-- Workflow definitions
INSERT INTO entities (kind, entity_id, data) VALUES ('workflow_definition', 'extract_integration_patterns', '{"definition_id": "extract_integration_patterns", "name": "Extract Integration Patterns", "description": "Scans a repository to identify, classify, and graph integration patterns and detect anti-patterns.", "is_template": false, "stage_names": ["scan_repo", "classify_integrations", "build_graph", "detect_antipatterns", "persist_results"], "graph_nodes": ["scan_repo", "classify_integrations", "build_graph", "detect_antipatterns", "persist_results"], "graph_edges": [["scan_repo", "classify_integrations"], ["classify_integrations", "build_graph"], ["build_graph", "detect_antipatterns"], ["detect_antipatterns", "persist_results"]], "entry_point": "scan_repo", "tags": ["integration", "architecture", "analysis"], "is_builtin": true, "enabled": true}'::jsonb) ON CONFLICT (kind, entity_id) DO UPDATE SET data = EXCLUDED.data, updated_at = now();

-- Agents
INSERT INTO entities (kind, entity_id, data) VALUES ('agent_definition', 'agent_integration_scanner', '{"agent_id": "agent_integration_scanner", "name": "Integration Scanner Agent", "role": "integration_scanner", "description": "Scans repositories to identify integration patterns, classify them by type, build dependency graphs, and detect anti-patterns such as tight coupling or missing retries.", "system_prompt": "You are an integration scanner agent. Analyse repository source code to identify all integration points including synchronous APIs (REST, gRPC, GraphQL), asynchronous messaging (Kafka, NATS, RabbitMQ, Redis pub-sub), database connections (SQLAlchemy, asyncpg, pymongo, redis, elasticsearch), file/blob storage (S3, Azure Blob, GCS, local file I/O), and third-party API clients. Classify each integration by type, build a service dependency graph with coupling scores, and flag anti-patterns such as tight coupling, missing retries, and chatty interfaces.", "model_provider": "anthropic", "model_name": "claude-sonnet-4-20250514", "max_tokens": 8192, "temperature": 0.1, "allowed_skill_ids": ["skill_scan_sync_integrations", "skill_scan_async_integrations", "skill_scan_db_integrations", "skill_scan_file_blob_integrations", "skill_scan_external_api_calls", "skill_detect_antipatterns", "skill_build_dependency_graph"], "tags": ["integration", "architecture"], "is_builtin": true, "enabled": true}'::jsonb) ON CONFLICT (kind, entity_id) DO UPDATE SET data = EXCLUDED.data, updated_at = now();

-- Skills
INSERT INTO entities (kind, entity_id, data) VALUES ('skill', 'skill_scan_sync_integrations', '{"skill_id": "skill_scan_sync_integrations", "name": "Scan Synchronous Integrations", "version": "1.0.0", "description": "Detects REST, gRPC, and GraphQL synchronous integrations in repository source code.", "category": "integration_analysis", "system_prompt": "Scan the provided source code to identify all synchronous integration points. Detect REST API calls (requests, httpx, aiohttp), gRPC client/server definitions, and GraphQL queries/mutations. For each integration, extract the target service, endpoint, HTTP method, and any retry or timeout configuration.", "user_prompt_template": "", "input_schema": {}, "output_schema": {}, "execution_mode": "inline", "allowed_agent_roles": ["integration_scanner"], "tags": ["integration", "rest", "grpc", "graphql", "synchronous"], "is_builtin": true, "enabled": true}'::jsonb) ON CONFLICT (kind, entity_id) DO UPDATE SET data = EXCLUDED.data, updated_at = now();
INSERT INTO entities (kind, entity_id, data) VALUES ('skill', 'skill_scan_async_integrations', '{"skill_id": "skill_scan_async_integrations", "name": "Scan Asynchronous Integrations", "version": "1.0.0", "description": "Detects Kafka, NATS, RabbitMQ, and Redis pub-sub asynchronous messaging patterns in repository source code.", "category": "integration_analysis", "system_prompt": "Scan the provided source code to identify all asynchronous messaging integration points. Detect Kafka producers/consumers, NATS publishers/subscribers, RabbitMQ channel usage, and Redis pub-sub patterns. For each integration, extract the topic/queue name, serialisation format, consumer group, and delivery guarantees.", "user_prompt_template": "", "input_schema": {}, "output_schema": {}, "execution_mode": "inline", "allowed_agent_roles": ["integration_scanner"], "tags": ["integration", "kafka", "nats", "rabbitmq", "redis", "asynchronous"], "is_builtin": true, "enabled": true}'::jsonb) ON CONFLICT (kind, entity_id) DO UPDATE SET data = EXCLUDED.data, updated_at = now();
INSERT INTO entities (kind, entity_id, data) VALUES ('skill', 'skill_scan_db_integrations', '{"skill_id": "skill_scan_db_integrations", "name": "Scan Database Integrations", "version": "1.0.0", "description": "Detects SQLAlchemy, asyncpg, pymongo, redis, and elasticsearch database usage patterns in repository source code.", "category": "integration_analysis", "system_prompt": "Scan the provided source code to identify all database integration points. Detect SQLAlchemy models and sessions, asyncpg connection pools, pymongo collections, redis client usage, and elasticsearch index operations. For each integration, extract the database type, connection configuration, query patterns, and connection pooling settings.", "user_prompt_template": "", "input_schema": {}, "output_schema": {}, "execution_mode": "inline", "allowed_agent_roles": ["integration_scanner"], "tags": ["integration", "database", "sqlalchemy", "asyncpg", "pymongo", "redis", "elasticsearch"], "is_builtin": true, "enabled": true}'::jsonb) ON CONFLICT (kind, entity_id) DO UPDATE SET data = EXCLUDED.data, updated_at = now();
INSERT INTO entities (kind, entity_id, data) VALUES ('skill', 'skill_scan_file_blob_integrations', '{"skill_id": "skill_scan_file_blob_integrations", "name": "Scan File and Blob Storage Integrations", "version": "1.0.0", "description": "Detects S3, Azure Blob, GCS, and local file I/O patterns in repository source code.", "category": "integration_analysis", "system_prompt": "Scan the provided source code to identify all file and blob storage integration points. Detect AWS S3 (boto3), Azure Blob Storage, Google Cloud Storage, and local filesystem I/O operations. For each integration, extract the storage provider, bucket/container names, access patterns (read/write/list), and any encryption or lifecycle configuration.", "user_prompt_template": "", "input_schema": {}, "output_schema": {}, "execution_mode": "inline", "allowed_agent_roles": ["integration_scanner"], "tags": ["integration", "s3", "azure-blob", "gcs", "file-io", "storage"], "is_builtin": true, "enabled": true}'::jsonb) ON CONFLICT (kind, entity_id) DO UPDATE SET data = EXCLUDED.data, updated_at = now();
INSERT INTO entities (kind, entity_id, data) VALUES ('skill', 'skill_scan_external_api_calls', '{"skill_id": "skill_scan_external_api_calls", "name": "Scan External API Calls", "version": "1.0.0", "description": "Detects third-party API client usage such as Stripe, Twilio, SendGrid, and other external service integrations.", "category": "integration_analysis", "system_prompt": "Scan the provided source code to identify all third-party API client usage. Detect SDK imports and HTTP calls to external services such as Stripe, Twilio, SendGrid, Slack, GitHub, and other SaaS APIs. For each integration, extract the provider, API version, authentication method, rate limiting configuration, and error handling approach.", "user_prompt_template": "", "input_schema": {}, "output_schema": {}, "execution_mode": "inline", "allowed_agent_roles": ["integration_scanner"], "tags": ["integration", "external-api", "third-party", "saas"], "is_builtin": true, "enabled": true}'::jsonb) ON CONFLICT (kind, entity_id) DO UPDATE SET data = EXCLUDED.data, updated_at = now();
INSERT INTO entities (kind, entity_id, data) VALUES ('skill', 'skill_detect_antipatterns', '{"skill_id": "skill_detect_antipatterns", "name": "Detect Integration Anti-Patterns", "version": "1.0.0", "description": "Rule-based detection of tight coupling, missing retries, and chatty interfaces across identified integrations.", "category": "integration_analysis", "system_prompt": "Analyse the identified integration points and apply rule-based detection for common anti-patterns. Check for tight coupling between services (direct database sharing, hardcoded URLs), missing retry and circuit-breaker logic on external calls, chatty interfaces (excessive fine-grained API calls instead of batch operations), missing timeouts, synchronous calls in hot paths that should be async, and absent error handling. Assign severity (low/medium/high/critical) and provide remediation guidance for each finding.", "user_prompt_template": "", "input_schema": {}, "output_schema": {}, "execution_mode": "inline", "allowed_agent_roles": ["integration_scanner"], "tags": ["integration", "antipattern", "coupling", "reliability"], "is_builtin": true, "enabled": true}'::jsonb) ON CONFLICT (kind, entity_id) DO UPDATE SET data = EXCLUDED.data, updated_at = now();
INSERT INTO entities (kind, entity_id, data) VALUES ('skill', 'skill_build_dependency_graph', '{"skill_id": "skill_build_dependency_graph", "name": "Build Dependency Graph", "version": "1.0.0", "description": "Aggregates scan results into a service dependency graph with coupling scores between components.", "category": "integration_analysis", "system_prompt": "Aggregate the results from all integration scans into a unified service dependency graph. For each pair of connected services, compute a coupling score based on the number of integration points, types of coupling (data, control, stamp), and presence of anti-patterns. Output the graph as a list of nodes (services) and weighted edges (dependencies) with metadata including integration type, coupling score, and identified risks.", "user_prompt_template": "", "input_schema": {}, "output_schema": {}, "execution_mode": "inline", "allowed_agent_roles": ["integration_scanner"], "tags": ["integration", "dependency-graph", "coupling", "architecture"], "is_builtin": true, "enabled": true}'::jsonb) ON CONFLICT (kind, entity_id) DO UPDATE SET data = EXCLUDED.data, updated_at = now();

COMMIT;
