"""Message history management: sliding window with LLM-based summarisation.

Provides ``MessageHistoryManager`` which trims a conversation message list to
stay within a configurable token budget. Older messages outside the sliding
window are replaced with a single summary message generated by the LLM.

Usage::

    manager = MessageHistoryManager(max_window=20, summary_model_callback=my_summarise)
    trimmed = await manager.apply(messages)
"""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from dataclasses import dataclass, field
from typing import Any

import structlog

logger = structlog.get_logger()

# Rough token estimate: 4 characters per token (conservative).
_CHARS_PER_TOKEN = 4

# Default maximum messages in the sliding window (including system prompt).
DEFAULT_MAX_WINDOW = 20

# Maximum token budget for the summary of evicted messages.
DEFAULT_SUMMARY_MAX_TOKENS = 512

# Messages shorter than this many characters are not worth summarising.
_MIN_EVICTION_CHARS = 200

# Role name used for the injected summary message.
SUMMARY_ROLE = "system"


def _estimate_tokens(messages: list[dict[str, Any]]) -> int:
    """Return a rough token count for a list of chat messages."""
    total_chars = sum(len(str(m.get("content", ""))) for m in messages)
    return total_chars // _CHARS_PER_TOKEN


def _format_messages_for_summary(messages: list[dict[str, Any]]) -> str:
    """Flatten messages into a compact text block for the summariser."""
    parts: list[str] = []
    for m in messages:
        role = m.get("role", "unknown")
        content = str(m.get("content", ""))
        if content:
            parts.append(f"[{role}] {content}")
    return "\n".join(parts)


@dataclass
class HistoryConfig:
    """Configuration for message history management."""

    max_window: int = DEFAULT_MAX_WINDOW
    summary_max_tokens: int = DEFAULT_SUMMARY_MAX_TOKENS
    max_total_tokens: int = 0  # 0 = no token-based limit, use window only
    preserve_system: bool = True  # always keep system messages at the front


@dataclass
class HistoryResult:
    """Result of applying history management to a message list."""

    messages: list[dict[str, Any]]
    evicted_count: int = 0
    summary_added: bool = False
    estimated_tokens: int = 0


# Type alias for the summarisation callback.
# Accepts the text to summarise, returns the summary string.
SummaryCallback = Callable[[str], Awaitable[str]]


@dataclass
class MessageHistoryManager:
    """Manages conversation history with a sliding window and optional summarisation.

    The manager splits messages into:
    1. **System messages** at the start (always preserved)
    2. **Older messages** outside the window (candidates for eviction/summarisation)
    3. **Recent messages** inside the window (always kept)

    When older messages are evicted, a summary is generated and injected as a
    system message right after the original system messages.
    """

    config: HistoryConfig = field(default_factory=HistoryConfig)
    summary_callback: SummaryCallback | None = None

    async def apply(self, messages: list[dict[str, Any]]) -> HistoryResult:
        """Apply sliding window + summarisation to *messages*.

        Returns a :class:`HistoryResult` with the trimmed message list and
        metadata about what was evicted.
        """
        if not messages:
            return HistoryResult(messages=[], estimated_tokens=0)

        # Separate leading system messages from the rest.
        system_msgs, conversation_msgs = self._split_system(messages)

        total_non_system = len(conversation_msgs)
        max_conversation = self.config.max_window - len(system_msgs)
        if max_conversation < 1:
            max_conversation = 1

        # Nothing to evict?
        if total_non_system <= max_conversation:
            return HistoryResult(
                messages=list(messages),
                estimated_tokens=_estimate_tokens(messages),
            )

        # Split into evicted (old) and kept (recent)
        eviction_boundary = total_non_system - max_conversation
        evicted = conversation_msgs[:eviction_boundary]
        kept = conversation_msgs[eviction_boundary:]

        # Optionally apply a token-based secondary trim on the kept window
        if self.config.max_total_tokens > 0:
            kept = self._trim_to_token_budget(
                kept,
                self.config.max_total_tokens - _estimate_tokens(system_msgs),
            )

        # Build the summary for evicted messages
        summary_msg: dict[str, Any] | None = None
        evicted_text = _format_messages_for_summary(evicted)

        if len(evicted_text) >= _MIN_EVICTION_CHARS and self.summary_callback is not None:
            try:
                summary_text = await self.summary_callback(evicted_text)
                summary_msg = {
                    "role": SUMMARY_ROLE,
                    "content": ("[Conversation summary of earlier messages]\n" + summary_text),
                }
                logger.info(
                    "history_summary_generated",
                    evicted_count=len(evicted),
                    summary_chars=len(summary_text),
                )
            except Exception:
                logger.warning("history_summary_failed", evicted_count=len(evicted))
        elif len(evicted_text) >= _MIN_EVICTION_CHARS:
            # No callback — generate a simple truncation notice
            summary_msg = {
                "role": SUMMARY_ROLE,
                "content": (
                    f"[{len(evicted)} earlier messages were trimmed from this conversation]"
                ),
            }

        # Assemble final message list
        result_messages: list[dict[str, Any]] = list(system_msgs)
        if summary_msg is not None:
            result_messages.append(summary_msg)
        result_messages.extend(kept)

        return HistoryResult(
            messages=result_messages,
            evicted_count=len(evicted),
            summary_added=summary_msg is not None,
            estimated_tokens=_estimate_tokens(result_messages),
        )

    def _split_system(
        self, messages: list[dict[str, Any]]
    ) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
        """Split leading system messages from the conversation body."""
        if not self.config.preserve_system:
            return [], list(messages)
        system_msgs: list[dict[str, Any]] = []
        for m in messages:
            if m.get("role") == "system":
                system_msgs.append(m)
            else:
                break
        return system_msgs, messages[len(system_msgs) :]

    @staticmethod
    def _trim_to_token_budget(messages: list[dict[str, Any]], budget: int) -> list[dict[str, Any]]:
        """Drop oldest messages until the list fits within *budget* tokens."""
        if budget <= 0:
            return messages
        while messages and _estimate_tokens(messages) > budget:
            messages = messages[1:]
        return messages


async def default_summary_callback(
    text: str,
    call_model: Callable[..., Awaitable[dict[str, Any]]],
    policy: Any,  # noqa: ANN401
) -> str:
    """A reusable summarisation callback that uses the model router.

    Callers should bind ``call_model`` and ``policy`` via :func:`functools.partial`
    or a closure before passing to :class:`MessageHistoryManager`.
    """
    result = await call_model(
        policy,
        messages=[
            {
                "role": "system",
                "content": (
                    "Summarise the following conversation excerpt concisely. "
                    "Preserve key decisions, action items, and technical details. "
                    "Omit greetings and filler. Output only the summary."
                ),
            },
            {"role": "user", "content": text},
        ],
    )
    return str(result.get("content", ""))
