"""Default guardrail rules shipped with Lintel (GRD-7)."""

from __future__ import annotations

from lintel.domain.guardrails.models import GuardrailAction, GuardrailRule

DEFAULT_RULES: tuple[GuardrailRule, ...] = (
    GuardrailRule(
        rule_id="d47f4a01-1c3a-4b8e-9f6d-0e1a2b3c4d51",
        name="agent_rework_warning",
        event_type="RunCompleted",
        condition="rework_rate > threshold",
        action=GuardrailAction.WARN,
        threshold=0.2,
        cooldown_seconds=300,
        is_default=True,
        enabled=True,
    ),
    GuardrailRule(
        rule_id="d47f4a01-1c3a-4b8e-9f6d-0e1a2b3c4d52",
        name="cost_warning",
        event_type="RunCompleted",
        condition="run_cost > threshold",
        action=GuardrailAction.WARN,
        threshold=5.0,
        cooldown_seconds=600,
        is_default=True,
        enabled=True,
    ),
    GuardrailRule(
        rule_id="d47f4a01-1c3a-4b8e-9f6d-0e1a2b3c4d53",
        name="cost_escalation",
        event_type="PullRequestCreated",
        condition="project_daily_cost > threshold",
        action=GuardrailAction.REQUIRE_APPROVAL,
        threshold=100.0,
        cooldown_seconds=3600,
        is_default=True,
        enabled=True,
    ),
    GuardrailRule(
        rule_id="d47f4a01-1c3a-4b8e-9f6d-0e1a2b3c4d54",
        name="sandbox_timeout",
        event_type="SandboxCommandFinished",
        condition="duration_seconds > threshold",
        action=GuardrailAction.WARN,
        threshold=1800.0,
        cooldown_seconds=60,
        is_default=True,
        enabled=True,
    ),
    GuardrailRule(
        rule_id="d47f4a01-1c3a-4b8e-9f6d-0e1a2b3c4d55",
        name="test_failure_block",
        event_type="TestResultRecorded",
        condition="verdict == 'failed'",
        action=GuardrailAction.BLOCK,
        threshold=None,
        cooldown_seconds=0,
        is_default=True,
        enabled=True,
    ),
    GuardrailRule(
        rule_id="d47f4a01-1c3a-4b8e-9f6d-0e1a2b3c4d56",
        name="large_diff_review",
        event_type="PullRequestCreated",
        condition="lines_changed > threshold",
        action=GuardrailAction.REQUIRE_APPROVAL,
        threshold=500.0,
        cooldown_seconds=0,
        is_default=True,
        enabled=True,
    ),
    GuardrailRule(
        rule_id="d47f4a01-1c3a-4b8e-9f6d-0e1a2b3c4d57",
        name="pii_in_artifacts",
        event_type="ArtifactCreated",
        condition="pii_detected == true",
        action=GuardrailAction.BLOCK,
        threshold=None,
        cooldown_seconds=0,
        is_default=True,
        enabled=True,
    ),
)
